### ISSUE TITLE
RTI Export Crashing 

### ISSUE THREAD

**Issue by jacopomazzoni** [cnr-isti-vclab/relight#22] opened 2021-03-25 22:40 UTC
see here: 

https://user-images.githubusercontent.com/9261308/112552592-5fc7c980-8dc3-11eb-9341-e27f4b0c2f15.mp4

**Comment by ponchio** [comment] 2021-03-26 04:29
I have made a few changes to the RTI export, could you test again?
In case the problem persists, could you send me the dataset, so I can look for the problem?

Thanks for the feedback.

**Comment by jacopomazzoni** [comment] 2021-03-26 09:29
Now it opens the small dialogue and creates these files but then still crashes:
```
Nsamples: 300000
Done in: 399029ms
Segmentation fault (core dumped)
```
![Screenshot from 2021-03-26 10-28-31](https://user-images.githubusercontent.com/9261308/112611453-207a9680-8e1e-11eb-9d0b-d7afecc70f80.png)
![Screenshot from 2021-03-26 10-28-21](https://user-images.githubusercontent.com/9261308/112611458-22dcf080-8e1e-11eb-9f43-8ea4b8c6925c.png)

**Comment by ponchio** [comment] 2021-03-26 14:41
I downloaded the file but the zip is corrupted, but I see the RTI is actually finished so the problem is most probably not with the datast but it might be either in the pyhon processing (did you select deepzoom or tarzoom as format?) or in the threads accessing some shared content.

It might lack some package in python and  I don't catch the correct exception.

Could you select 'relight' format and test? Thanks.

**Comment by jacopomazzoni** [comment] 2021-03-26 21:33
when I compile rtiexport I do get some warinings:
```
[ 39%] Building CXX object relight/CMakeFiles/relight.dir/rtiexport.cpp.o
In file included from /usr/include/python2.7/Python.h:88,
                 from /home/jacopo/relight/relight/pybind11/include/pybind11/detail/common.h:124,
                 from /home/jacopo/relight/relight/pybind11/include/pybind11/pytypes.h:12,
                 from /home/jacopo/relight/relight/pybind11/include/pybind11/cast.h:13,
                 from /home/jacopo/relight/relight/pybind11/include/pybind11/attr.h:13,
                 from /home/jacopo/relight/relight/pybind11/include/pybind11/pybind11.h:45,
                 from /home/jacopo/relight/relight/rtiexport.cpp:2:
/usr/include/python2.7/unicodeobject.h:534:24: warning: ISO C++17 does not allow ‘register’ storage class specifier [-Wregister]
     register PyObject *obj,     /* Object */
                        ^~~
/usr/include/python2.7/unicodeobject.h:553:24: warning: ISO C++17 does not allow ‘register’ storage class specifier [-Wregister]
     register PyObject *obj      /* Object */
                        ^~~
/usr/include/python2.7/unicodeobject.h:575:29: warning: ISO C++17 does not allow ‘register’ storage class specifier [-Wregister]
     register const wchar_t *w,  /* wchar_t buffer */
                             ^
/usr/include/python2.7/unicodeobject.h:593:23: warning: ISO C++17 does not allow ‘register’ storage class specifier [-Wregister]
     register wchar_t *w,        /* wchar_t buffer */
                       ^
In file included from /usr/include/python2.7/Python.h:97,
                 from /home/jacopo/relight/relight/pybind11/include/pybind11/detail/common.h:124,
                 from /home/jacopo/relight/relight/pybind11/include/pybind11/pytypes.h:12,
                 from /home/jacopo/relight/relight/pybind11/include/pybind11/cast.h:13,
                 from /home/jacopo/relight/relight/pybind11/include/pybind11/attr.h:13,
                 from /home/jacopo/relight/relight/pybind11/include/pybind11/pybind11.h:45,
                 from /home/jacopo/relight/relight/rtiexport.cpp:2:
/usr/include/python2.7/stringobject.h:173:24: warning: ISO C++17 does not allow ‘register’ storage class specifier [-Wregister]
     register PyObject *obj, /* string or Unicode object */
                        ^~~
/usr/include/python2.7/stringobject.h:174:21: warning: ISO C++17 does not allow ‘register’ storage class specifier [-Wregister]
     register char **s,  /* pointer to buffer variable */
                     ^
/usr/include/python2.7/stringobject.h:175:26: warning: ISO C++17 does not allow ‘register’ storage class specifier [-Wregister]
     register Py_ssize_t *len /* pointer to length variable or NULL
                          ^~~
```

**Comment by ponchio** [comment] 2021-03-26 21:35
I think the problem is that I am using python3.6, not python 2.7.

Sorry I added python just a couple of days ago and it takes a little
testing to sort it out.

**Comment by jacopomazzoni** [comment] 2021-03-26 21:48
Should I install 3.6 as well? is there a specific package i can download to match your configuration?

**Comment by ponchio** [comment] 2021-03-26 21:57
I am using 3.6, just because it was the installed version. 

At the moment there are no tensor flow or cuda packages planened, most probably any 3.x should work (include and lib compiler options might need to be adjusted.

I would go with 3.6.9 (sudo apt-get install python3.6 should install that version), just to be sure.
You will also need to install libvips for python3, (pip3 probably will be installed as a package manager).
This is for the deepzoom functionality (and tarzoom).
Later python will be used for dome calibration, photogrammetry and other stuff.

**Comment by jacopomazzoni** [comment] 2021-03-26 22:48
that might not be the problem i just tried this:
```
jacopo@pop-os:~$ python3 --version
Python 3.8.6

```

**Comment by ponchio** [comment] 2021-03-26 22:51
Sorry, wrong package: pyvips is the correct one.

Probably it's easier if we just have a call and try to solve the issues interactively.

ponchio@gmail.com, anytime you want (from 10am on).

**Comment by jacopomazzoni** [comment] 2021-03-26 23:16
I tried this:
`pip install --user pyvips`
but still can't export to deepzoom
`Nsamples: 300000
Done in: 338894ms
Segmentation fault (core dumped)
`
I would be very grateful for any assistance.
I'll send you an email with my phone number.

**Closed** 2021-08-30 07:35 UTC
